"""empty message

Revision ID: 0d52c2aca8a0
Revises: 59bade2abe29
Create Date: 2021-07-31 20:07:52.062443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d52c2aca8a0'
down_revision = '59bade2abe29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('is_seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.alter_column('Artist', 'name',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('Artist', 'city',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.alter_column('Artist', 'state',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.alter_column('Artist', 'phone',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.alter_column('Artist', 'genres',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.add_column('Venue', sa.Column('genres', sa.String(length=160), nullable=False))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('is_seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.alter_column('Venue', 'name',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('Venue', 'city',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.alter_column('Venue', 'state',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.alter_column('Venue', 'address',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    op.alter_column('Venue', 'phone',
                existing_type=sa.VARCHAR(length=120),
                nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'phone',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Venue', 'address',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Venue', 'state',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Venue', 'city',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Venue', 'name',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'is_seeking_talent')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genres')
    op.alter_column('Artist', 'genres',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Artist', 'phone',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Artist', 'state',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Artist', 'city',
                existing_type=sa.VARCHAR(length=120),
                nullable=True)
    op.alter_column('Artist', 'name',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'is_seeking_venue')
    # ### end Alembic commands ###
