"""empty message

Revision ID: 521966f080da
Revises: 0d52c2aca8a0
Create Date: 2021-07-31 20:43:24.424176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521966f080da'
down_revision = '0d52c2aca8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
